---
apiVersion: v1
kind: Secret
metadata:
  name: helm-docker-registry-secret
  namespace: dso-argocd
type: Opaque
stringData:
  username: <path:forge-dso/data/env/conf-dso/apps/common/values#dockerAccount | jsonPath {.username}>
  password: <path:forge-dso/data/env/conf-dso/apps/common/values#dockerAccount | jsonPath {.password}>
