pgdump_cnpg_clusters:
  - name: "{{ dsc.keycloak.subDomain }}"
    namespace: "{{ dsc.keycloak.namespace }}"
    db: keycloak
  - name: "{{ dsc.sonarqube.subDomain }}"
    namespace: "{{ dsc.sonarqube.namespace }}"
    db: sonardb
  - name: "{{ dsc.gitlab.subDomain }}"
    namespace: "{{ dsc.gitlab.namespace }}"
    db: gitlabhq_production
  - name: "{{ dsc.harbor.subDomain }}"
    namespace: "{{ dsc.harbor.namespace }}"
    db: registry
  - name: "{{ dsc.console.subDomain }}"
    namespace: "{{ dsc.console.namespace }}"
    db: dso-console-db
