apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-cluster-keycloak
  namespace: conftest-keycloak
spec:
  backupOwnerReference: self
  cluster:
    name: pg-cluster-keycloak
  schedule: 0 0 0 * * *
