---
- name: Hard refresh argocd applications
  when: kubeconfig_infra is defined
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_infra }}"
    proxy: "{{ kubeconfig_proxy_infra | default('')}}"
    kind: Application
    api_version: argoproj.io/v1alpha1
    name: "{{ item }}"
    namespace: "{{ dsc.argocdInfra.namespace }}"
    definition:
      metadata:
        annotations:
          argocd.argoproj.io/refresh: "hard"
    state: patched

- name: Sync argocd applications
  when: kubeconfig_infra is defined
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_infra }}"
    proxy: "{{ kubeconfig_proxy_infra | default('')}}"
    kind: Application
    api_version: argoproj.io/v1alpha1
    name: "{{ item }}"
    namespace: "{{ dsc.argocdInfra.namespace }}"
    definition:
      operation:
        initiatedBy:
          username: GitOpsAnsible
        sync:
          syncStrategy:
            hook: {}
    state: patched
