- name: Get secret
  kubernetes.core.k8s_info:
    name: "{{ dsc.global.backup.s3.endpointCA.name }}"
    namespace: "{{ dsc.global.backup.s3.endpointCA.namespace }}"
    kind: Secret
  register: cnpg_s3_ca_resource

- name: Extract key
  ansible.builtin.set_fact:
    cnpg_s3_ca_pem: "{{ cnpg_s3_ca_resource.resources[0].data[dsc.global.backup.s3.endpointCA.key] }}"
