{
 "title": "Console",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods up",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"dso-cpn-console-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"dso-cpn-console-.*\", container!=\"POD\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC available space (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"(.*-)*console(-.*)*\",namespace=\"$namespace\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"(.*-)*console(-.*)*\",namespace=\"$namespace\"} * 100, 0.01)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}