---
vault_secrets_post_install: false
envs:
  - name: "{{ dsc_name }}"
    apps:
      - argocd_app: "common"
        vault_values:
          image:
            repository:
              docker: "{{ dsc.global.registry | default('docker.io') }}"
              ghcr: "{{ dsc.global.registry | default('ghcr.io') }}"
          domain:
            keycloak: "{{ keycloak_domain }}"
            console: "{{ console_domain }}"
            observatorium: "{{ observatorium_domain }}"
            sonarqube: "{{ sonar_domain }}"
          proxy:
            httpProxy: "{{ dsc.proxy.http_proxy | default('') }}"
            httpsProxy: "{{ dsc.proxy.https_proxy | default('') }}"
            noProxy: "{{ dsc.proxy.no_proxy | default('') }}"
            hostProxy: "{{ dsc.proxy.host | default('') }}"
            portProxy: "{{ dsc.proxy.port | default('') }}"
          cnpgS3CaPem: "{{ cnpg_s3_ca_pem | default('') }}"
          externalClusters:
            pgCluster:
              barmanObjectStore:
                destinationPath: "s3://{{ dsc.global.backup.s3.bucketName | default('') }}/{{ dsc.global.backup.cnpg.pathPrefix | default('') }}"
                endpointURL: "{{ dsc.global.backup.s3.endpointURL | default('') }}"
                s3Credentials:
                  accessKeyId:
                    value: "{{ dsc.global.backup.s3.credentials.accessKeyId.value | default ('') }}"
                  secretAccessKey:
                    value: "{{ dsc.global.backup.s3.credentials.secretAccessKey.value | default('') }}"
      - argocd_app: "keycloak"
        vault_values:
          auth:
            adminPassword: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
          initcontainers:
            pluginDownloadUrl: "{{ dsc.keycloak.pluginDownloadUrl }}"
      - argocd_app: "observatorium"
        vault_values:
          ingress:
            ingressClassName: "{{ dsc.ingress.className }}"
          api:
            loglevel: info
            config:
              id: "prod-infra"
              name: "prod-infra"
          logs:
            enabled: "{{ dsc.global.logs.enabled }}"
            endpoint: "{{ dsc.global.logs.endpoint }}"
          metrics:
            enabled: "{{ dsc.global.metrics.enabled }}"
            endpoint: "{{ dsc.global.metrics.endpoint }}"
      - argocd_app: "sonarqube"
        vault_values:
          auth:
            adminPassword: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
            monitoringPassword: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"
