apiVersion: v1
data:
  admin-password: <path:forge-dso/data/env/conf-dso/apps/keycloak/values#auth | jsonPath
    {.adminPassword} | base64encode>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: 'true'
  name: keycloak
type: Opaque
