---
- name: Installation du socle DSO
  hosts: localhost
  gather_facts: false

  roles:
    - name: socle-config
      tags:
        - always

    - name: ca
      tags:
        - always

    - name: console-dso-config
      tags:
        - always

    - name: cert-manager
      tags:
        - cert-manager
        - cm

    - name: confSyncer
      tags:
        - confSyncer
        - kubed

    - name: cloudnativepg
      tags:
        - cloudnativepg
        - cnpg

    - name: keycloak
      tags:
        - keycloak
        - sso

    - name: nexus
      tags:
        - nexus

    - name: sonarqube
      tags:
        - sonarqube
        - sonar

    - name: gitlab-operator
      tags:
        - gitlab-operator

    - name: gitlab
      tags:
        - gitlab

    - name: gitlab-catalog
      tags:
        - catalog
        - gitlab-catalog

    - name: gitlab-runner
      tags:
        - runner
        - gitlab-runner

    - name: vault
      tags:
        - vault

    - name: argocd
      tags:
        - gitops
        - argocd
        - argo

    - name: harbor
      tags:
        - harbor
        - registry

    - name: console-dso
      tags:
        - console
        - console-dso

    - name: grafana-operator
      tags:
        - grafana-operator
        - never

    - name: grafana
      tags:
        - grafana
        - never

    - name: grafana-datasource
      tags:
        - grafana-datasource
        - never

    - name: grafana-dashboards
      tags:
        - grafana-dashboards
        - never

  post_tasks:
    - name: Post-Install Disclaimer
      ansible.builtin.debug:
        msg: "{{ dsc | get_debug_messages }}"
      tags:
        - always
