- name: Installation du socle DSO
  hosts: localhost
  gather_facts: false

  roles:
    - name: socle-config
      tags:
        - always

    - name: ca
      tags:
        - always

    - name: console-dso-config
      tags:
        - always

    - name: cert-manager
      tags:
        - cert-manager
        - always

    - name: confSyncer
      tags:
        - confSyncer
        - kubed

    - name: cloudnativepg
      tags:
        - cloudnativepg
        - always

#    - name: keycloak
    - name: keycloak-helm
      tags:
        - keycloak

    - name: nexus
      tags:
        - nexus

    - name: sonarqube
      tags:
        - sonarqube

    - name: gitlab
      tags:
        - gitlab

    - name: gitlab-catalog
      tags:
        - catalog

    - name: gitlab-runner
      tags:
        - gitlab-runner

    - name: vault
      tags:
        - vault

    - name: sops
      tags:
        - sops

    - name: argocd
      tags:
        - gitops
        - argocd

    - name: harbor
      tags:
        - harbor
        - registry

    - name: console-dso
      tags:
        - console
        - console-dso
