---
- name: Installation du socle DSO en mode GitOps
  hosts: localhost
  gather_facts: false

  roles:
    - role: socle-config
      tags:
        - always

    - role: check-prerequisite
      tags:
        - always

    - role: cluster-offline
      tags:
        - always
      when: dsc.global.offline

    - role: imagepullsecret
      tags:
        - always
      when: use_image_pull_secrets

    - role: prometheus
      tags:
        - prometheus
        - prom
      when: dsc.prometheus.crd.type == 'managed'

    - role: infra/keycloak-infra
      tags:
        - keycloak-infra
        - sso-infra
      when: dsc.keycloakInfra.installEnabled

    - role: infra/vault-infra
      tags:
        - vault-infra
      when: dsc.vaultInfra.installEnabled

    - role: infra/argocd-infra
      tags:
        - gitops-infra
        - argocd-infra
        - argo-infra
      when: dsc.argocdInfra.installEnabled

    - role: gitops/local-config
      tags:
        - rendering-apps-files
        - apps-files
        - dso-app
        - vault-secrets

    - role: gitops/vault-secrets
      tags:
        - vault-secrets

    - role: gitops/rendering-apps-files
      tags:
        - rendering-apps-files
        - apps-files

    - role: gitops/watchpoint
      tags:
        - gitops-watchpoint
        - watchpoint
      when: dsc.global.gitOps.watchpointEnabled

    - role: gitops/dso-app
      tags:
        - dso-app
