---
- name: Installation du socle DSO en mode GitOps
  hosts: localhost
  gather_facts: false

  roles:
    - role: socle-config
      tags:
        - always

    - role: check-prerequisite
      tags:
        - always

    - role: ca
      tags:
        - always

    - role: console-dso-config
      tags:
        - always

    - role: imagepullsecret
      tags:
        - always
      when: use_image_pull_secrets

    - role: prometheus
      tags:
        - prometheus
        - prom
      when: dsc.prometheus.crd.type == 'managed'

    - role: kyverno
      tags:
        - kyverno

    - role: cloudnativepg
      tags:
        - cloudnativepg
        - cnpg

    - role: infra/keycloak-infra
      tags:
        - keycloak-infra
        - sso-infra
      when: dsc.keycloakInfra.installEnabled

    - role: infra/vault-infra
      tags:
        - vault-infra
      when: dsc.vaultInfra.installEnabled

    - role: infra/argocd-infra
      tags:
        - gitops-infra
        - argocd-infra
        - argo-infra
      when: dsc.argocdInfra.installEnabled

    - role: gitops/local-config
      tags:
        - rendering-apps-files
        - apps-files
        - dso-app
        - vault-secrets
        - vault-secrets-post-install
        - post-install
        - post-install-vault

    - role: gitops/vault-secrets
      tags:
        - vault-secrets
        - post-install
        - post-install-nexus

    - role: gitops/rendering-apps-files
      tags:
        - rendering-apps-files
        - apps-files
        - post-install
        - post-install-vault
        - vault-secrets-post-install

    - role: gitops/watchpoint
      tags:
        - gitops-watchpoint
        - watchpoint
      when: dsc.global.gitOps.watchpointEnabled

    - role: gitops/dso-app
      tags:
        - dso-app

    - name: gitops/post-install/vault
      tags:
        - post-install
        - post-install-vault
        - vault-secrets-post-install

  tasks:
    - name: Load variables for the vault-secrets post-install role
      ansible.builtin.include_vars:
        file: roles/gitops/vault-secrets/vars/post-install.yaml
      tags:
        - vault-secrets-post-install

    - name: Post-install vault-secrets run
      ansible.builtin.import_role:
        name: gitops/vault-secrets
      tags:
        - vault-secrets-post-install
