---
- name: Installation du socle DSO en mode GitOps
  hosts: localhost
  gather_facts: false

  roles:
    - name: socle-config
      tags:
        - always

    - name: ca
      tags:
        - always

    - name: console-dso-config
      tags:
        - always

    - name: gitops/kubeview
      tags:
        - kubeview

