---
- name: Installation du socle DSO
  hosts: localhost
  gather_facts: false

  roles:
    - role: socle-config
      tags:
        - always

    - role: cluster-offline
      tags:
        - always
      when: dsc.global.offline

    - role: ca
      tags:
        - always

    - role: console-dso-config
      tags:
        - always

    - name: imagepullsecret
      tags:
        - always
      when: use_image_pull_secrets

    - role: kyverno
      tags:
        - kyverno

    - role: cert-manager
      tags:
        - cert-manager
        - cm
        - always

    - role: cloudnativepg
      tags:
        - cloudnativepg
        - cnpg

    - role: prometheus
      tags:
        - prometheus
        - prom
      when: dsc.prometheus.crd.type == 'managed'

    - role: keycloak
      tags:
        - keycloak
        - sso

    - name: infra/keycloak-infra
      tags:
        - keycloak-infra
        - sso-infra
      when: dsc.keycloakInfra.installEnabled

    - role: nexus
      tags:
        - nexus

    - role: sonarqube
      tags:
        - sonarqube
        - sonar

    - role: gitlab-operator
      tags:
        - gitlab-operator

    - role: gitlab
      tags:
        - gitlab

    - role: gitlab-catalog
      tags:
        - catalog
        - gitlab-catalog

    - role: gitlab-runner
      tags:
        - runner
        - gitlab-runner

    - role: gitlab-ci-pipelines-exporter
      tags:
        - ci-pipelines-exporter
        - gitlab-ci-pipelines-exporter
      when: not dsc.global.offline

    - role: vault
      tags:
        - vault

    - name: infra/vault-infra
      tags:
        - vault-infra
      when: dsc.vaultInfra.installEnabled

    - role: argocd
      tags:
        - gitops
        - argocd
        - argo

    - name: infra/argocd-infra
      tags:
        - gitops-infra
        - argocd-infra
        - argo-infra
      when: dsc.argocdInfra.installEnabled

    - role: harbor
      tags:
        - harbor
        - registry

    - role: console-dso
      tags:
        - console
        - console-dso

    - role: grafana-operator
      tags:
        - grafana-operator
        - grafana-stack
        - never

    - role: grafana
      tags:
        - grafana
        - grafana-stack
        - never

    - role: grafana-datasource
      tags:
        - grafana-datasource
        - grafana-stack
        - never

    - role: grafana-dashboards
      tags:
        - grafana-dashboards
        - grafana-stack
        - never

  post_tasks:
    - name: Post-Install Disclaimer
      ansible.builtin.debug:
        msg: "{{ dsc | get_debug_messages }}"
      tags:
        - always
