- hosts: localhost
  gather_facts: false

  roles:
    - name: socle-config
      tags:
        - always

  post_tasks:
    - name: Suppression des namespaces
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ item }}"
      with_items:
        - "{{ DSC.console.namespace }}"
        - "{{ DSC.sops.namespace }}"
        - "{{ DSC.sonarqube.namespace }}"
        - "{{ DSC.vault.namespace }}"
        - "{{ DSC.nexus.namespace }}"
        - "{{ DSC.harbor.namespace }}"
        - "{{ DSC.argocd.namespace }}"

    - name: Récupérations des clients Keycloak
      kubernetes.core.k8s_info:
        api_version: keycloak.org/v1alpha1
        kind: KeycloakClient
        namespace: "{{ DSC.keycloak.namespace }}"
      register: keycloak_clients

    - name: Suppression des clients Keycloak
      kubernetes.core.k8s:
        state: absent
        api_version: keycloak.org/v1alpha1
        kind: KeycloakClient
        name: "{{ item.metadata.name }}"
        namespace: "{{ DSC.keycloak.namespace }}"
      with_items: "{{ keycloak_clients.resources }}"

    - name: Suppression des ressources Keycloak
      kubernetes.core.k8s:
        state: absent
        api_version: keycloak.org/v1alpha1
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: "{{ DSC.keycloak.namespace }}"
      with_items:
        - kind: KeycloakRealm
          name: dso-realm
        - kind: KeycloakUser
          name: admin-gitlab

    - name: Suppression du gitlab runner
      kubernetes.core.k8s:
        state: absent
        api_version: apps.gitlab.com/v1beta2
        kind: Runner
        name: gitlab-runner
        namespace: "{{ DSC.gitlab.namespace }}"

    - name: Suppression des namespaces restants
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ item }}"
      with_items:
        - "{{ DSC.keycloak.namespace }}"
        - "{{ DSC.gitlab.namespace }}"
        - cluster-infra

    - name: Remove local vars
      ansible.builtin.file:
        state: absent
        path: vars.yaml
      tags:
        - always
