---
- name: Vérifier si l'exécution du playbook déprécié est autorisée
  ansible.builtin.fail:
    msg:
      - /!\ Ce playbook est déprécié et ne devrait plus être utilisé. /!\
      - Nous vous recommandons d'utiliser l'installation en mode GitOps.
      - Si vous souhaitez l'exécuter quand même, exportez la variable d'environnement
      - export DSO_ALLOW_DEPRECATED=1
  when: dso_allow_deprecated | default(false) | bool == false

- name: /!\ Avertissement ! vous exécutez un playbook déprécié /!\
  ansible.builtin.debug:
    msg: "Vous avez autorisé l'exécution du playbook déprécié (DSO_ALLOW_DEPRECATED=1)"
  when: dso_allow_deprecated | bool
