{
 "title": "GitLab - Gitaly",
 "description": "GitLab Gitaly service metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gitlab-gitaly\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Git Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_build_info{job=\"gitlab-gitaly\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"gitlab-gitaly\"}",
     "legendFormat": "Go routines {{instance}}"
    },
    {
     "expr": "process_open_fds{job=\"gitlab-gitaly\"}",
     "legendFormat": "Open FDs"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"gitlab-gitaly\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitlab-gitaly\"}",
     "legendFormat": "RSS - {{instance}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"gitlab-gitaly\"}",
     "legendFormat": "Next GC - {{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (grpc_method,grpc_service,grpc_type) (\n  rate(grpc_server_started_total{job=\"gitlab-gitaly\"}[$__interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}