- name: Get GitLab token
  ansible.builtin.set_fact:
    gitlab_token: "{{ ansible_inventory.resources[0].data.GITLAB_TOKEN | b64decode }}"
  when: ansible_inventory.resources[0].data.GITLAB_TOKEN is defined and ansible_inventory.resources[0].data.GITLAB_TOKEN | length != 0
  register: set_token_inv

- name: Test GitLab token
  when: set_token_inv.skipped is not defined
  ansible.builtin.uri:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    url: https://{{ gitlab_domain }}/api/v4/admin/ci/variables
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
  register: test_token
  ignore_errors: true

- name: Initialize GitLab token
  when: (set_token_inv.skipped is defined and set_token_inv.skipped) or (test_token.status != 200)
  block:
    - name: Get toolbox pod name
      kubernetes.core.k8s_info:
        kind: pod
        label_selectors:
          - app = toolbox
        namespace: "{{ dsc.gitlab.namespace }}"
      register: toolbox_pods

    - name: Set toolbox pod name
      ansible.builtin.set_fact:
        tb_pod: "{{ toolbox_pods.resources[0].metadata.name }}"

    - name: Create token
      ansible.builtin.include_tasks:
        file:
          "{{ dsc.gitlab.chartVersion is version('7.2.0', operator='lt', version_type='loose') |
          ternary('create-token-7.2.0-.yaml', 'create-token-7.2.0+.yaml') }}"

    - name: Set new GitLab token
      ansible.builtin.set_fact:
        gitlab_token: "{{ token.stdout_lines[-2][1:-1] }}"

    - name: Update inventory
      kubernetes.core.k8s:
        kind: Secret
        name: dso-config
        namespace: "{{ dsc.console.namespace }}"
        state: patched
        definition:
          data:
            GITLAB_TOKEN: "{{ gitlab_token | b64encode }}"

- name: Get GitLab token
  when: (set_token_inv.skipped is not defined or not set_token_inv.skipped) and (test_token.status == 200)
  block:
    - name: Find gitlab token in inventory
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.console.namespace }}"
        kind: Secret
        name: dso-config
      register: ansible_inventory

    - name: Set GitLab token
      ansible.builtin.set_fact:
        gitlab_token: "{{ ansible_inventory.resources[0].data.GITLAB_TOKEN | b64decode }}"
