---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: dso-vault
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: vault
spec:
  tls:
    - hosts:
        - <path:forge-dso/data/env/conf-dso/apps/common/values#domain | jsonPath {.vault}>
      secretName: vault-tls-secret
  ingressClassName: nginx
  rules:
    - host: <path:forge-dso/data/env/conf-dso/apps/common/values#domain | jsonPath {.vault}>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conf-dso-vault-active
                port:
                  number: 8200
