---
- name: Get cluster infos
  kubernetes.core.k8s_cluster_info:
  register: cluster_infos

- name: Create Grafana Operator namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ dsc.grafanaOperator.namespace }}"
    state: present

- name: Create Grafana instances namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ dsc.grafana.namespace }}"
    state: present

- name: Set path facts
  ansible.builtin.set_fact:
    path: "{{ role_path + '/templates/values' }}"
    chart_path: "{{ role_path + '/chart/grafana-instances' }}"

- name: Compute Grafana Operator Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc.grafanaOperator['values'] }}"
    combine_dest_var: "operator_values"

- name: Deploy Grafana Operator helm
  kubernetes.core.helm:
    name: grafana-operator
    chart_ref: "{{ dsc.grafanaOperator.ociChartUrl }}"
    chart_version: "{{ dsc.grafanaOperator.chartVersion }}"
    release_namespace: "{{ dsc.grafanaOperator.namespace }}"
    create_namespace: true
    values: "{{ operator_values }}"
    wait: true
    timeout: 300s
  register: helm_deploy
  failed_when: "'status' not in helm_deploy or helm_deploy.status.status != 'deployed'"

- name: Wait grafana-operator-metrics-service endpoint
  kubernetes.core.k8s_info:
    kind: Endpoints
    namespace: "{{ dsc.grafanaOperator.namespace }}"
    name: grafana-operator-metrics-service
  register: endpoint
  until: endpoint.resources[0].subsets[0].addresses[0] is defined
  retries: 15
  delay: 5

- name: Ensure Grafana Keycloak Secret exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-keycloak
        namespace: "{{ dsc.grafana.namespace }}"
      type: Opaque
      data:
        client_id: "{{ 'grafana' | b64encode }}"
        client_secret: "{{ 'grafana' | b64encode }}"
  when: not lookup('k8s', kind='Secret', name='grafana-keycloak', namespace=(dsc.grafana.namespace)) | bool

- name: Get Grafana Keycloak Secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: grafana-keycloak
    namespace: "{{ dsc.grafana.namespace }}"
  register: keycloak_secret
  failed_when: keycloak_secret.resources | length == 0

- name: Deploy Grafana instances Helm chart
  kubernetes.core.helm:
    name: grafana-instances
    chart_ref: "{{ chart_path }}"
    release_namespace: "{{ dsc.grafana.namespace }}"
    create_namespace: true
    values: "{{ operator_values }}"
    wait: true
    timeout: 300s
  register: helm_instances_deploy
  failed_when: "'status' not in helm_instances_deploy or helm_instances_deploy.status.status != 'deployed'"
