apiVersion: v1
data:
  monitoring-password: <path:forge-dso/data/env/conf-dso/apps/sonarqube/values#auth
    | jsonPath {.monitoringPassword} | base64encode>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: 'true'
  name: sonar-monitoring-password
type: Opaque
