kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonar-monitoring-password
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  monitoring-password: <path:forge-dso/data/env/conf-dso/apps/sonarqube/values#auth | jsonPath {.monitoringPassword} | base64encode>
