apiVersion: v1
data:
  currentPassword: YWRtaW4=
  password: <path:forge-dso/data/env/conf-dso/apps/sonarqube/values#auth | jsonPath
    {.adminPassword} | base64encode>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: 'true'
  name: sonarqube
type: Opaque
