- name: Find GitLab token in inventory
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.console.namespace }}"
    kind: Secret
    name: dso-config
  register: ansible_inventory

- name: Get GitLab token
  ansible.builtin.set_fact:
    gitlab_token: "{{ ansible_inventory.resources[0].data.GITLAB_TOKEN | b64decode }}"
  when: ansible_inventory.resources[0].data.GITLAB_TOKEN is defined and ansible_inventory.resources[0].data.GITLAB_TOKEN | length != 0
  register: set_token_inv

- name: Test GitLab token
  when: set_token_inv.skipped is not defined
  ansible.builtin.uri:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    url: https://{{ gitlab_domain }}/api/v4/admin/ci/variables
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
  register: test_token
  ignore_errors: true

- name: Get GitLab token
  when: (set_token_inv.skipped is not defined or not set_token_inv.skipped) and (test_token.status == 200)
  block:
    - name: Find gitlab token in inventory
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.console.namespace }}"
        kind: Secret
        name: dso-config
      register: ansible_inventory

    - name: Set GitLab token
      ansible.builtin.set_fact:
        gitlab_token: "{{ ansible_inventory.resources[0].data.GITLAB_TOKEN | b64decode }}"
