---
- name: Create Argo CD application
  kubernetes.core.k8s:
    name: "{{ dsc_name }}-argocd"
    namespace: "{{ dsc.argocdInfra.namespace }}"
    api_version: argoproj.io/v1alpha1
    kind: Application
    state: present
    template: argocd.yaml.j2
