---
- name: Create dso-install-manager application in infrastructure ArgoCD cluster/namespace
  when: not (argo_infra_ns_check.resources | length == 0)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_infra }}"
    proxy: "{{ kubeconfig_proxy_infra | default('')}}"
    namespace: dsc.argocdInfra.namespace
    definition: "{{ lookup('ansible.builtin.template', role_path + '/templates/dso-app.yaml.j2') | from_yaml }}"
    state: present

- name: Create dso-appset destination dir
  ansible.builtin.file:
    path: "{{ gitops_local_repo }}/{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ dsc.global.gitOps.repo.path }}"
    - applicationSets

- name: Calculate all distinct configured sync waves
  ansible.builtin.set_fact:
    distinct_waves: "{{ envs | map(attribute='apps') | flatten | map(attribute='syncWave') | unique | sort }}"

- name: Render dso-appset template for each sync-waves and write yaml files to destination dir
  vars:
    rendered_content: "{{ lookup('ansible.builtin.template', role_path + '/templates/dso-appset.yaml.j2') }}"
  ansible.builtin.copy:
    content: "{{ rendered_content }}"
    dest: "{{ gitops_local_repo }}/applicationSets/dso-appset-wave-{{ sync_wave }}.yaml"
    mode: "0644"
  loop: "{{distinct_waves}}"
  loop_control:
    loop_var: sync_wave

- name: Create dummy secret to tell Argocd to use avp plugin # We need to check if we can improve this
  ansible.builtin.template:
    src: avp-plugin-trigger.yaml.j2
    dest: "{{ gitops_local_repo }}/applicationSets/avp-plugin-trigger.yaml"
    mode: "0644"
