vault:
  csi:
    agent:
      image:
        repository: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#global
          | jsonPath {.image.repository}>/hashicorp/vault
    image:
      repository: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#global
        | jsonPath {.image.repository}>/hashicorp/vault-csi-provider
  global:
    serverTelemetry:
      prometheusOperator: false
  injector:
    agentImage:
      repository: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#global
        | jsonPath {.image.repository}>/hashicorp/vault
    image:
      repository: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#global
        | jsonPath {.image.repository}>/hashicorp/vault-k8s
    metrics:
      enabled: false
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      pod:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
  server:
    auditStorage:
      enable: true
    dataStorage:
      enable: true
      size: 23Gi
    ha:
      apiAddr: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#server | jsonPath
        {.ha.apiAddr}>
      enabled: true
      raft:
        enabled: true
      replicas: 3
    image:
      repository: <path:forge-dso/data/env/dso-hp-testcm/apps/vault/values#global
        | jsonPath {.image.repository}>/hashicorp/vault
    route:
      enabled: false
    standalone:
      enabled: false
    statefulSet:
      securityContext:
        container:
          allowPrivilegeEscalation: false
        pod:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 100
  serverTelemetry:
    serviceMonitor:
      enabled: false
