---
- name: Get cluster infos
  kubernetes.core.k8s_cluster_info:
  register: cluster_infos

- name: Check if CloudNativePG operator api exists
  ansible.builtin.set_fact:
    cnpg_api: "{{ cluster_infos.apis['postgresql.cnpg.io/v1'] | default('absent') }}"

- name: Check if cnpg-mutating-webhook-configuration exists
  kubernetes.core.k8s_info:
    kind: MutatingWebhookConfiguration
    name: cnpg-mutating-webhook-configuration
  register: cnpg_mwhc

- name: Install CloudNativePG operator
  when: >
    cnpg_api == 'absent' or
    cnpg_mwhc.resources | length == 0 or
    dsc.cloudnativepg.forcedInstall
  block:
    - name: Create CloudNativePG namespace
      kubernetes.core.k8s:
        name: "{{ dsc.cloudnativepg.namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Add CloudNativePG helm repo
      kubernetes.core.helm_repository:
        name: cnpg
        repo_url: "{{ dsc.cloudnativepg.helmRepoUrl }}"
        force_update: true

    - name: Set path fact
      ansible.builtin.set_fact:
        path: "{{ role_path + '/templates/values' }}"

    - name: Compute Gitlab Helm values
      ansible.builtin.include_role:
        name: combine
      vars:
        combine_path: "{{ path }}"
        combine_user_values: "{{ dsc.cloudnativepg['values'] }}"
        combine_dest_var: "cnpg_values"

    - name: Deploy CloudNativePG helm
      kubernetes.core.helm:
        name: cloudnative-pg
        chart_ref: cnpg/cloudnative-pg
        chart_version: "{{ dsc.cloudnativepg.chartVersion }}"
        release_namespace: "{{ dsc.cloudnativepg.namespace }}"
        values: "{{ cnpg_values }}"

    - name: Wait cnpg-webhook-service endpoint
      kubernetes.core.k8s_info:
        kind: Endpoints
        namespace: "{{ dsc.cloudnativepg.namespace }}"
        name: cnpg-webhook-service
      register: endpoint
      until: endpoint.resources[0].subsets[0].addresses[0] is defined
      retries: 15
      delay: 5

    - name: Set alerting rules
      when: dsc.global.alerting.enabled
      kubernetes.core.k8s:
        template: prometheusrule.yml.j2
