---
- name: Get proxy cache PVC info
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.nexus.namespace }}"
    name: nexus-data-proxy-cache
    kind: PersistentVolumeClaim
  register: nexus_proxy_cache

- name: Manage incorrect storage pvc size
  when: (nexus_proxy_cache.resources | length) and (nexus_proxy_cache.resources[0].status.capacity.storage != dsc.nexus.proxyCacheSize)
  block:
    - name: Disclaimer Storage downsize
      when: nexus_proxy_cache.resources[0].status.capacity.storage[:-2] > dsc.nexus.proxyCacheSize[:-2]
      ansible.builtin.fail:
        msg:
          - Operation Cancelled.
          - You want to downsize dsc.nexus.proxyCacheSize, and we can't do it.
          - Please change value and try again or operate pvc manually.

    - name: Disclaimer Bad storage unit size
      when: nexus_proxy_cache.resources[0].status.capacity.storage[-2:] != dsc.nexus.proxyCacheSize[-2:]
      ansible.builtin.fail:
        msg:
          - Operation Cancelled.
          - You are trying to use another storage unit, and we can't ensure it works.
          - Please change value and try again or operate pvc manually.

    - name: Delete Nexus deployment
      kubernetes.core.helm:
        name: "{{ dsc.nexus.release }}"
        release_namespace: "{{ dsc.nexus.namespace }}"
        state: absent

    - name: Wait end of deletion
      kubernetes.core.k8s_info:
        api_version: v1
        kind: pod
        namespace: "{{ dsc.nexus.namespace }}"
      register: nexus_pod
      until: nexus_pod.resources | length == 0
      retries: 5

- name: Create both PVCs
  kubernetes.core.k8s:
    template: pvc.yml.j2
