- name: get PVC info
  kubernetes.core.k8s_info:
    namespace: "{{ DSC.nexus.namespace }}"
    name: nexus-data-claim
    kind: PersistentVolumeClaim
  register: nexus_pvc


- name: manage incorrect pvc size
  when: (nexus_pvc.resources | length) and (nexus_pvc.resources[0].status.capacity.storage != DSC.nexus.storageSize)
  block:
    - name: Disclaimer Storage downsize
      when: nexus_pvc.resources[0].status.capacity.storage[:-2] > DSC.nexus.storageSize[:-2]
      fail:
        msg:
          - Operation Cancelled.
          - You want to downsize DSC.nexus.storageSize, and we can't do it.
          - Please change value and try again or operate pvc manually.

    - name: Disclaimer Bad storage unit size
      when: nexus_pvc.resources[0].status.capacity.storage[-2:] != DSC.nexus.storageSize[-2:]
      fail:
        msg:
          - Operation Cancelled.
          - You are trying to use another storage unit, and we can't ensure it works.
          - Please change value and try again or operate pvc manually.

    - name: Delete deployment
      kubernetes.core.k8s:
        template: nexus.yml.j2
        state: absent

    - name: Wait end of deletion
      kubernetes.core.k8s_info:
        api_version: v1
        kind: pod
        namespace: "{{ DSC.nexus.namespace }}"
      register: nexus_pod
      until: nexus_pod.resources | length == 0
      retries: 5

- name: Create PVC
  kubernetes.core.k8s:
    template: pvc.yml.j2
