---
- name: Update or create inventory secret (dso-config)
  kubernetes.core.k8s:
    kind: Secret
    name: dso-config
    namespace: "{{ dsc.console.namespace }}"
    state: patched
    definition:
      apiVersion: v1
      metadata:
        name: dso-config
        namespace: "{{ dsc.console.namespace }}"
      data:
        NEXUS_ADMIN_PASSWORD: "{{ nexus_current_vault_values.stdout | from_json | json_query('auth.adminPassword') | b64encode }}"
