values:
  argocd:
    configs: |
      rbac:
        scopes: "[groups]"
        policy.default: role:nada
        admin.enabled: "false"
        policy.csv: |
          p, role:admin, *, *, */*, allow
          p, role:nada, applicationsets, *, */*, deny
          p, role:nada, applications, *, */*, deny
          p, role:nada, logs, *, */*, deny
          p, role:nada, exec, *, */*, deny
          p, role:nada, certificates, *, *, deny
          p, role:nada, accounts, *, *, deny
          p, role:nada, gpgkeys, *, *, deny
          p, role:nada, projects, *, *, deny
          p, role:nada, clusters, *, *, deny
          p, role:nada, repositories, get, *, allow
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
          g, /admin, role:admin
          g, admin, role:admin

    cm: |
      resource.exclusions: |
        - apiGroups:
          - tekton.dev
          clusters:
          - '*'
          kinds:
          - TaskRun
          - PipelineRun
        - apiGroups:
          - wgpolicyk8s.io
          - aquasecurity.github.io
          clusters:
          - '*'
          kinds:
          - '*'
        - apiGroups:
          - postgresql.cnpg.io
          clusters:
          - '*'
          kinds:
          - Backup
        - apiGroups:
          - reports.kyverno.io
          clusters:
          - '*'
          kinds:
          - EphemeralReport
        - apiGroups:
          - reports.kyverno.io/v1
          clusters:
          - '*'
          kinds:
          - EphemeralReport
      oidc.config: |
        issuer: https://<path:{{ vaultinfra_kv_name }}/data/env/{{ dsc_name }}/apps/common/values#domain | jsonPath {.keycloak}>/realms/dso
        requestedScopes: ["openid", "generic"]
        name: Keycloak
        clientID: <path:{{ vaultinfra_kv_name }}/data/env/{{ dsc_name }}/apps/keycloak/values#client | jsonPath {.argo.id}>
        clientSecret: <path:{{ vaultinfra_kv_name }}/data/env/{{ dsc_name }}/apps/keycloak/values#client | jsonPath {.argo.secret}>

    rootCA_block: |
      rootCA: |
        <path:{{ vaultinfra_kv_name }}/data/env/conf-dso/apps/common/values#exposedCa | indent 2>
