---
# Set admin facts and check access to Keycloak API

- name: Get Keycloak admin password
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.keycloak.namespace }}"
    kind: Secret
    name: keycloak
  register: kc_adm_pass

- name: Set Keycloak admin facts
  ansible.builtin.set_fact:
    keycloak_admin_password: "{{ kc_adm_pass.resources[0].data['admin-password'] | b64decode }}"
    keycloak_admin: admin

- name: Get Keycloak API token
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/realms/{{ dsc.keycloak.managementRealm }}/protocol/openid-connect/token"
    method: POST
    status_code: [200, 202]
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    return_content: true
    body: username={{ keycloak_admin }}&password={{ keycloak_admin_password }}&grant_type=password&client_id=admin-cli
  register: kc_token
  ignore_errors: true

- name: Reset Keycloak admin fact
  when: kc_token is failed
  ansible.builtin.set_fact:
    keycloak_admin: dsoadmin

- name: Get Keycloak API token
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/realms/{{ dsc.keycloak.managementRealm }}/protocol/openid-connect/token"
    method: POST
    status_code: [200, 202]
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    return_content: true
    body: username={{ keycloak_admin }}&password={{ keycloak_admin_password }}&grant_type=password&client_id=admin-cli
  register: kc_token

- name: Set kc_access_token fact
  ansible.builtin.set_fact:
    kc_access_token: "{{ kc_token.json.access_token }}"

# Create permanent Keycloak admin and update DSO Console inventory

- name: Get keycloak master realm users from API
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ dsc.keycloak.managementRealm }}/users"
    method: GET
    status_code: [200, 202]
    return_content: true
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    body_format: json
    headers:
      Authorization: bearer {{ kc_access_token }}
  register: kc_master_users

- name: Set permanent_admin_present fact
  ansible.builtin.set_fact:
    permanent_admin_present: false

- name: Update admin_present fact
  when: kc_master_users.json | selectattr('username', 'equalto', 'dsoadmin')
  ansible.builtin.set_fact:
    permanent_admin_present: true

- name: Create permanent admin group and user into master realm
  when: not permanent_admin_present
  block:
    - name: Create admin group
      community.general.keycloak_group:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_auth_url }}"
        auth_realm: "{{ dsc.keycloak.managementRealm }}"
        auth_username: "{{ keycloak_admin }}"
        auth_password: "{{ keycloak_admin_password }}"
        name: admin
        realm: "{{ dsc.keycloak.managementRealm }}"
        state: present

    - name: Map admin realm role from admin group
      community.general.keycloak_realm_rolemapping:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        realm: "{{ dsc.keycloak.managementRealm }}"
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_auth_url }}"
        auth_realm: "{{ dsc.keycloak.managementRealm }}"
        auth_username: "{{ keycloak_admin }}"
        auth_password: "{{ keycloak_admin_password }}"
        state: present
        group_name: admin
        roles:
          - name: admin

    - name: Create master realm permanent admin user
      community.general.keycloak_user:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_auth_url }}"
        auth_realm: "{{ dsc.keycloak.managementRealm }}"
        auth_username: "{{ keycloak_admin }}"
        auth_password: "{{ keycloak_admin_password }}"
        state: present
        realm: "{{ dsc.keycloak.managementRealm }}"
        credentials:
          - temporary: false
            type: password
            value: "{{ keycloak_admin_password }}"
        username: dsoadmin
        first_name: Admin
        last_name: Admin
        email: admin@example.com
        enabled: true
        email_verified: true
        groups:
          - name: admin
            state: present

# Remove Keycloak temporary admin

- name: Set temporary_admin_present fact
  ansible.builtin.set_fact:
    temporary_admin_present: false

- name: Update temporary_admin_present fact
  when: kc_master_users.json | selectattr('username', 'equalto', 'admin')
  ansible.builtin.set_fact:
    temporary_admin_present: true

- name: Remove temporary admin from master realm
  when: temporary_admin_present
  community.general.keycloak_user:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    state: absent
    realm: "{{ dsc.keycloak.managementRealm }}"
    username: admin

# Ensure we will use permanent admin for subsequent tasks

- name: Get Keycloak API token
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/realms/{{ dsc.keycloak.managementRealm }}/protocol/openid-connect/token"
    method: POST
    status_code: [200, 202]
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    return_content: true
    body: username={{ keycloak_admin }}&password={{ keycloak_admin_password }}&grant_type=password&client_id=admin-cli
  register: kc_token
  ignore_errors: true

- name: Reset Keycloak admin fact
  when: kc_token is failed
  ansible.builtin.set_fact:
    keycloak_admin: dsoadmin

- name: Get Keycloak API token
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/realms/{{ dsc.keycloak.managementRealm }}/protocol/openid-connect/token"
    method: POST
    status_code: [200, 202]
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    return_content: true
    body: username={{ keycloak_admin }}&password={{ keycloak_admin_password }}&grant_type=password&client_id=admin-cli
  register: kc_token

- name: Set kc_access_token fact
  ansible.builtin.set_fact:
    kc_access_token: "{{ kc_token.json.access_token }}"

# Create and setup dso realm

- name: Create dso realm
  community.general.keycloak_realm:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    state: present
    id: "{{ dsc.keycloak.applicationRealm }}"
    realm: "{{ dsc.keycloak.applicationRealm }}"
    display_name: Dso Realm
    loginWithEmailAllowed: true
    registration_email_as_username: false
    loginTheme: DSFR
    accountTheme: DSFR
    adminTheme: DSFR
    emailTheme: DSFR
    internationalizationEnabled: true
    supportedLocales:
      - en
      - fr
    defaultLocale: fr
    password_policy: >
      length(15) and lowerCase(1) and upperCase(1) and specialChars(1) and digits(1) and
      passwordHistory(2) and notUsername() and forceExpiredPasswordChange(183)
    enabled: true
    otp_policy_algorithm: SHA256
    reset_password_allowed: true
    action_token_generated_by_user_lifespan: 900
    smtp_server:
      host: "{{ (dsc.global.smtp | default({})).host | default(omit) }}"
      port: "{{ (dsc.global.smtp | default({})).port | default(omit) }}"
      from: "{{ (dsc.global.smtp | default({})).from | default(omit) }}"
      user: "{{ (dsc.global.smtp.authentication | default({})).user | default(omit) }}"
      password: "{{ (dsc.global.smtp.authentication | default({})).password | default(omit) }}"
      auth: "{{ dsc.global.smtp.authentication.enabled }}"
      starttls: "{{ dsc.global.smtp.starttlsEnabled }}"

- name: Create base admins groups
  community.general.keycloak_group:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    state: present
    realm: "{{ dsc.keycloak.applicationRealm }}"
    name: admin

- name: Get keycloak dso realm users from API
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ dsc.keycloak.applicationRealm }}/users"
    method: GET
    status_code: [200, 202]
    return_content: true
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    body_format: json
    headers:
      Authorization: bearer {{ kc_access_token }}
  register: kc_dso_users

- name: Find dso admin secret
  kubernetes.core.k8s_info:
    namespace: "{{ dsc.keycloak.namespace }}"
    kind: Secret
    name: dso-admin-user-secret
  register: dso_admin_secret

- name: Create dso admin secret and user
  when: >
    (dso_admin_secret.resources | length == 0) or
    (kc_dso_users.json | selectattr('username', 'equalto', dso_admin_secret.resources[0].data.ADMIN_USER|b64decode) | length == 0)
  block:
    - name: Generate admin user password
      ansible.builtin.set_fact:
        admin_user_password: "{{ lookup('community.general.random_string', length=16, min_lower=1, min_upper=1, min_special=1, min_numeric=1) }}"

    - name: Create dso secret
      kubernetes.core.k8s:
        definition:
          kind: Secret
          metadata:
            namespace: "{{ dsc.keycloak.namespace }}"
            name: dso-admin-user-secret
          data:
            ADMIN_USER: "{{ 'admin@example.com' | b64encode }}"
            ADMIN_USER_PASSWORD: "{{ admin_user_password | b64encode }}"
          type: Opaque

    - name: Remove dso admin user
      community.general.keycloak_user:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_auth_url }}"
        auth_realm: "{{ dsc.keycloak.managementRealm }}"
        auth_username: "{{ keycloak_admin }}"
        auth_password: "{{ keycloak_admin_password }}"
        state: absent
        realm: "{{ dsc.keycloak.applicationRealm }}"
        username: admin@example.com

    - name: Create dso admin user
      community.general.keycloak_user:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_auth_url }}"
        auth_realm: "{{ dsc.keycloak.managementRealm }}"
        auth_username: "{{ keycloak_admin }}"
        auth_password: "{{ keycloak_admin_password }}"
        state: present
        realm: "{{ dsc.keycloak.applicationRealm }}"
        credentials:
          - temporary: false
            type: password
            value: "{{ admin_user_password }}"
        username: admin@example.com
        first_name: Admin
        last_name: Admin
        email: admin@example.com
        enabled: true
        email_verified: true
        groups:
          - name: admin
            state: present
#        force: true # Ne fonctionne pas quand user supprimé via l'interface graphique et tâche relancée.

- name: Get dso keycloak client scopes from API
  ansible.builtin.uri:
    url: "{{ keycloak_auth_url }}/admin/realms/{{ dsc.keycloak.applicationRealm }}/client-scopes"
    method: GET
    status_code: [200, 202]
    return_content: true
    body_format: json
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    headers:
      Authorization: bearer {{ kc_access_token }}
  register: kc_client_scopes

- name: Create generic keycloak client scope
  when: kc_client_scopes.json | selectattr('name', 'equalto', 'generic') | length == 0
  community.general.keycloak_clientscope:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    name: generic
    realm: "{{ dsc.keycloak.applicationRealm }}"
    description: Generic client scope
    protocol: openid-connect
    attributes:
      include.in.token.scope: true
      display.on.consent.screen: true
      gui.order: ""
      consent.screen.text: ""
    protocolMappers: "{{ lookup('ansible.builtin.file', 'generic-client-scope-protocolMappers.yaml') | from_yaml }}"

- name: Create group keycloak client scope
  when: kc_client_scopes.json | selectattr('name', 'equalto', 'group') | length == 0
  community.general.keycloak_clientscope:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    name: group
    realm: "{{ dsc.keycloak.applicationRealm }}"
    description: Group client scope
    protocol: openid-connect
    attributes:
      include.in.token.scope: true
      display.on.consent.screen: true
      gui.order: ""
      consent.screen.text: ""
    protocolMappers: "{{ lookup('ansible.builtin.file', 'group-client-scope-protocolMappers.yaml') | from_yaml }}"

- name: Create clients
  ansible.builtin.include_tasks:
    file: client.yaml
  loop: "{{ keycloak_clients }}"

- name: Enable brute force detection
  community.general.keycloak_realm:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "{{ dsc.keycloak.managementRealm }}"
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ item }}"
    brute_force_protected: true
    failure_factor: 10
  with_items:
    - "{{ dsc.keycloak.managementRealm }}"
    - "{{ dsc.keycloak.applicationRealm }}"

- name: Set GitLab OIDC provider fact
  block:
    - name: Get Gitlab client secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: "{{ dsc.keycloak.namespace }}"
        name: keycloak-client-secret-gitlab-client
      register: gitlab_secret
      failed_when: gitlab_secret.resources | length == 0

    - name: Define GitLab OIDC provider secret content
      ansible.builtin.set_fact:
        gitlab_oidc_provider: |
          name: openid_connect
          label: Keycloak
          args:
            name: openid_connect
            scope:
              - openid
              - generic
            response_type: code
            issuer: https://{{ keycloak_domain }}/realms/{{ dsc.keycloak.applicationRealm }}
            client_auth_method: query
            discovery: true
            uid_field: email
            client_options:
              identifier: {{ gitlab_secret.resources[0].data.CLIENT_ID | b64decode }}
              secret: {{ gitlab_secret.resources[0].data.CLIENT_SECRET | b64decode }}
              redirect_uri: https://{{ gitlab_domain }}/users/auth/openid_connect/callback

- name: Reconcile keycloak users
  when: dsc.keycloak.usersGitOpsEnabled
  ansible.builtin.include_tasks:
    file: sync_users.yml
