apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: infra-argocd
spec:
  destination:
    namespace: dso-grafana
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: dso-grafana
    repoURL: https://cloud-pi-native.github.io/helm-charts
    targetRevision: 1.0.0
    helm:  
      values: |
        {{ .Values.grafana | toYaml | nindent 8 }}
      valueFiles:
      - ./values.yaml
      - $tenants/helm/values.yaml
  - ref: tenants
    repoURL: "https://gitlab.sdid-hp.cpin.numerique-interieur.com/observability/observability.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
