apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observatorium
  namespace: infra-argocd
spec:
  destination:
    namespace: dso-observatorium
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: observatorium
    repoURL: https://cloud-pi-native.github.io/helm-charts
    targetRevision: 0.5.2
    helm:  
      values: |
        {{ .Values.observatorium | toYaml | nindent 8 }}
      valueFiles:
      - ./values.yaml
      - $tenants/helm/values.yaml
  - ref: tenants
    repoURL: "https://<path:forge-dso/data/env/conf-dso/apps/common/values#domain | jsonPath {.gitlab}>/observability/observability.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
