apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observatorium
  namespace: infra-argocd
spec:
  destination:
    namespace: dso-observability
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: observatorium
    repoURL: https://cloud-pi-native.github.io/helm-charts
    targetRevision: 0.5.2
    helm:  
      values: |
        {{ .Values.observatorium | toYaml | nindent 8 }}
      valueFiles:
      - ./values.yaml
      - $tenants/helm/values.yaml
  - ref: tenants
    repoURL: "https://gitlab.sdid-hp.cpin.numerique-interieur.com/observability/observability.git"
    targetRevision: main
  syncPolicy:
    automated: {}
