apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: observability-gitlab-token
  namespace: infra-argocd
type: Opaque
stringData:
  password: <path:forge-dso/data/env/conf-dso/apps/gitlab/values#gitlabToken>
  url: "https://<path:forge-dso/data/env/conf-dso/apps/common/values#domain | jsonPath {.gitlab}>/observability/observability.git"
  username: "root"
