---
- name: Console post-configuration
  hosts: localhost
  gather_facts: false
  vars:
    post_conf_job: true
    argo_infra_ns_check:
      failed: true
  tasks:
    - name: Import socle-config role
      ansible.builtin.import_role:
        name: socle-config

    - name: Get pg-cluster-console-app secret
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.console.namespace }}"
        kind: Secret
        name: pg-cluster-console-app
      register: pg_console_db_secret

    - name: Update vault-secrets console uri
      block:
        - name: Reset envs vars
          ansible.builtin.set_fact:
            envs: []

        - name: Set minimal envs vars
          ansible.builtin.set_fact:
            envs:
              - name: "{{ dsc_name }}"
                apps:
                  - argocd_app: console
                    vault_values:
                      uri: >-
                        {{
                          (pg_console_db_secret.resources[0].data.uri | b64decode)
                          if pg_console_db_secret is defined and
                          pg_console_db_secret.resources | length > 0
                          else ''
                        }}

        - name: Post-install vault-secrets run
          ansible.builtin.import_role:
            name: gitops/vault-secrets
          vars:
            vault_secrets_post_install: true
            post_vault_update: true
