---
- name: Sonarqube post-configuration
  hosts: localhost
  gather_facts: false
  vars:
    post_conf_job: true
    argo_infra_ns_check:
      failed: true
  tasks:
    - name: Import socle-config role
      ansible.builtin.import_role:
        name: socle-config

    - name: Import sonarqube role
      ansible.builtin.import_role:
        name: gitops/post-install/sonarqube

    - name: Update vault-secrets sonarApiToken
      block:
        - name: Reset envs vars
          ansible.builtin.set_fact:
            envs: []

        - name: Set minimal envs vars
          ansible.builtin.set_fact:
            envs:
              - name: "{{ dsc_name }}"
                apps:
                  - argocd_app: sonarqube
                    vault_values:
                      auth:
                        sonarApiToken: >-
                          {{
                            (retrieved_token_pass.json.token)if retrieved_token_pass.json.token is defined and
                            retrieved_token_pass.json.token | length > 0
                            else ''
                          }}

        - name: Post-install vault-secrets run
          ansible.builtin.import_role:
            name: gitops/vault-secrets
          vars:
            vault_secrets_post_install: true
            post_vault_update: true
