---
- name: Check Argo CD infra namespace
  kubernetes.core.k8s_info:
    kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG_INFRA' ) }}"
    proxy: "{{ lookup('ansible.builtin.env', 'KUBECONFIG_PROXY_INFRA', default='') }}"
    name: "{{ dsc.argocdInfra.namespace }}"
    kind: Namespace
  register: argo_infra_ns_check
  ignore_errors: true
