{
 "title": "Nexus",
 "description": "Nexus Dashboard by KL",
 "tags": [ "nexus" ],
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_vm_uptime{job=\"nexus\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Heap Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_heap_usage{job=\"nexus\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "FileDescriptor Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_fd_usage{job=\"nexus\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Readonly Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "readonly_enabled{job=\"nexus\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Nexus Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FileBlobStore",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "copy - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "copy - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "deleteHard - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "deleteHard - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "get - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "get - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "delete - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "delete - p99"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "create - p50"
    },
    {
     "expr": "org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "create - p99"
    }
   ]
  },
  {
   "title": "RepositoryComponent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "getBrowseableFormats - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "getBrowseableFormats - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "readReferences - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "readReferences - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_read_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_RepositoryComponent_read_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "SecurityComponent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "getPermissions - p50"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "getPermissions - p99"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "getUser - p50"
    },
    {
     "expr": "org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "getUser - p99"
    }
   ]
  },
  {
   "title": "UserComponent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_readSources_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "readSources - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_readSources_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "readSources - p99"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_read_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_UserComponent_read_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "LdapServerComponent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "verifyLogin - p50"
    },
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "verifyLogin - p99"
    },
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_update_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "update - p50"
    },
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_update_timer{quantile=\"0.99\"}",
     "legendFormat": "update - p99"
    },
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_read_timer{quantile=\"0.5\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_read_timer{quantile=\"0.99\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "BrowseComponent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_BrowseComponent_read_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "read - p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_BrowseComponent_read_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "SearchComponent Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_sonatype_nexus_coreui_SearchComponent_read_timer{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "org_sonatype_nexus_coreui_SearchComponent_read_timer{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Component Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_sonatype_nexus_coreui_BlobStoreComponent_readGroups_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "BlobStoreComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_blobstore_s3_internal_ui_S3Component_signertypes_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "S3Component"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_TaskComponent_update_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "TaskComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_rapture_internal_state_StateComponent_getState_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "StateComponent"
    },
    {
     "expr": "rate(com_sonatype_nexus_migration_ui_AssistantComponent_cancel_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "AssistantComponent-Cancel"
    },
    {
     "expr": "rate(com_sonatype_nexus_migration_ui_AssistantComponent_abort_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "AssistantComponent-Abort"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_FreezeComponent_update_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "FreezeComponent-Update"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_FreezeComponent_read_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "FreezeComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_SelectorComponent_readReferences_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "SelectorComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_RepositoryComponent_rebuildIndex_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "RepositoryComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "LdapServerComponent"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_BrowseComponent_read_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "BrowseComponent"
    },
    {
     "expr": "rate(com_sonatype_nexus_clm_internal_ui_ClmComponent_readApplications_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "ClmComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_internal_capability_CapabilityComponent_remove_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "CapabilityComponent-Remove"
    },
    {
     "expr": "rate(com_sonatype_nexus_ssl_plugin_internal_ui_CertificateComponent_details_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "CertificateComponent-Details"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_SearchComponent_read_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "SearchComponent-Read"
    },
    {
     "expr": "rate(org_sonatype_nexus_rapture_internal_security_SecurityComponent_authenticate_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "SecurityComponent-Authenticate"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_changeOrder_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "LdapServerComponent-ChangeOrder"
    },
    {
     "expr": "rate(org_sonatype_nexus_coreui_RepositoryComponent_remove_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "RepositoryComponent-Remove"
    },
    {
     "expr": "rate(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_readReferences_exceptions_total{job=\"nexus\"}[5m])",
     "legendFormat": "LdapServerComponent-Read"
    }
   ]
  },
  {
   "title": "Jetty WebAppContext",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jetty Responses Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_1xx_responses_total{job=\"nexus\"}[1m])",
     "legendFormat": "1xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_2xx_responses_total{job=\"nexus\"}[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_5xx_responses_total{job=\"nexus\"}[1m])",
     "legendFormat": "5xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_4xx_responses_total{job=\"nexus\"}[1m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_3xx_responses_total{job=\"nexus\"}[1m])",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Jetty Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.5\", job=\"nexus\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.99\", job=\"nexus\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Jetty ThreadPool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_eclipse_jetty_util_thread_QueuedThreadPool_qtp612364006_jobs",
     "legendFormat": "wait-jobs"
    },
    {
     "expr": "org_eclipse_jetty_util_thread_QueuedThreadPool_qtp612364006_size",
     "legendFormat": "current-size"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_garbage_collectors_MarkSweepCompact_count{job=\"nexus\"}[1m])",
     "legendFormat": "major GC(marksweep)"
    },
    {
     "expr": "rate(jvm_garbage_collectors_PS_Scavenge_count{job=\"nexus\"}[1m])",
     "legendFormat": "minor GC(scavenge)"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_garbage_collectors_MarkSweepCompact_time{job=\"nexus\"}[5m]) / rate(jvm_garbage_collectors_MarkSweepCompact_count{job=\"nexus\"}[5m])",
     "legendFormat": "major GC(marksweep)"
    },
    {
     "expr": "rate(jvm_garbage_collectors_PS_Scavenge_time{job=\"nexus\"}[5m])/rate(jvm_garbage_collectors_PS_Scavenge_count{job=\"nexus\"}[5m])",
     "legendFormat": "minor GC(scavenge)"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_heap_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_heap_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_non_heap_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_non_heap_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_non_heap_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_total_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_total_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_total_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Eden_Space_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Eden_Space_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Eden_Space_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Tenured Gen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Tenured_Gen_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Tenured_Gen_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Tenured_Gen_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Survivor_Space_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Survivor_Space_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Survivor_Space_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Metaspace_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Metaspace_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Metaspace_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Compressed_Class_Space_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_Code_Cache_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pools_Code_Cache_max{job=\"nexus\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_pools_Code_Cache_committed{job=\"nexus\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffers_direct_count{job=\"nexus\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffers_direct_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffers_direct_capacity{job=\"nexus\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffers_mapped_count{job=\"nexus\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffers_mapped_used{job=\"nexus\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffers_mapped_capacity{job=\"nexus\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_thread_states_daemon_count{job=\"nexus\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_thread_states_terminated_count{job=\"nexus\"}",
     "legendFormat": "terminated"
    },
    {
     "expr": "jvm_thread_states_count{job=\"nexus\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_thread_states_new_count{job=\"nexus\"}",
     "legendFormat": "new"
    },
    {
     "expr": "jvm_thread_states_runnable_count{job=\"nexus\"}",
     "legendFormat": "runnable"
    },
    {
     "expr": "jvm_thread_states_blocked_count{job=\"nexus\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "jvm_thread_states_deadlock_count{job=\"nexus\"}",
     "legendFormat": "deadlock"
    },
    {
     "expr": "jvm_thread_states_timed_waiting_count{job=\"nexus\"}",
     "legendFormat": "timed_waiting"
    },
    {
     "expr": "jvm_thread_states_waiting_count{job=\"nexus\"}",
     "legendFormat": "waiting"
    }
   ]
  }
 ]
}