{
 "title": "SonarQube",
 "description": "System metrics for Sonarqube",
 "panels": [
  {
   "title": "System info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"dso-sonarqube/sonarqube\", namespace=\"dso-sonarqube\", pod=\"sonarqube-sonarqube-0\"}"
    }
   ]
  },
  {
   "title": "Virtual memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"dso-sonarqube/sonarqube\", namespace=\"dso-sonarqube\", pod=\"sonarqube-sonarqube-0\"}"
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"dso-sonarqube/sonarqube\", namespace=\"dso-sonarqube\", pod=\"sonarqube-sonarqube-0\"}"
    }
   ]
  },
  {
   "title": "CPU time usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"dso-sonarqube/sonarqube\"}"
    }
   ]
  },
  {
   "title": "JVM memory Heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\", job=\"dso-sonarqube/sonarqube\"} - jvm_memory_bytes_used{area=\"heap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "JVM memory NonHeap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\", job=\"dso-sonarqube/sonarqube\"} - jvm_memory_bytes_used{area=\"nonheap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max request time",
   "type": "timeseries",
   "description": "Maximum time to process a request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Tomcat_GlobalRequestProcessor_maxTime{job=\"dso-sonarqube/sonarqube\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}