---

- name: Gitops message
  ansible.builtin.debug:
    msg:
      - "Paramètre global.gitOps.watchpointEnabled positionné à true dans votre resource dsc '{{ dsc_name }}'."
      - "Arrêt de l'installation suite à génération automatique des fichiers d'applications pour l'environnement '{{ dsc_name }}'."
      - ""
      - "Veuillez vous assurer de la cohérence des fichiers générés dans le répertoire './gitops/envs/{{ dsc_name }}/apps'."
      - ""
      - "Vous devrez par ailleurs créer le fichier './gitops/envs/{{ dsc_name }}/{{ dsc_name }}.json' s'il n'existe pas déjà"
      - "et y ajuster les paramètres souhaités. Se référer à la documentation README à ce sujet."
      - ""
      - "Une fois ces vérifications et ajustements réalisés, poussez les fichiers modifiés dans votre dépôt Git (via 'git push')."
      - ""
      - "Pour finir vous pouvez soit :"
      - "- Lancer les roles d'installation restants via les tags appropriés."
      - "- Positionner le paramètre global.gitOps.watchpointEnabled à false dans"
      - "  votre resource dsc '{{ dsc_name }}' puis relancer une installation complète."

- name: Break execution
  ansible.builtin.meta: end_play
