---

- name: Gitops message
  ansible.builtin.debug:
    msg:
      - "Paramètre global.gitOps.watchpointEnabled positionné à true dans votre resource dsc '{{ dsc_name }}'."
      - "Arrêt de l'installation suite à génération automatique des fichiers d'applications pour l'environnement '{{ dsc_name }}'."
      - ""
      - "Veuillez vous assurer de la cohérence des fichiers générés dans le répertoire '{{ gitops_local_repo }}/{{ dsc.global.gitOps.repo.path }}/envs/{{ dsc_name }}/apps'."
      - ""
      - "Vous devrez par ailleurs adapter le fichier '{{ gitops_local_repo }}/{{ dsc.global.gitOps.repo.path }}/envs/{{ dsc_name }}/{{ dsc_name }}.json'"
      - "afin d'y ajuster les paramètres souhaités. Se référer à la documentation README à ce sujet."
      - ""
      - "Assurez-vous également de la cohérence des secrets qui ont été générés dans votre instance Vault d'infrastructure,"
      - "au niveau du secret engine '{{ vaultinfra_kv_name }}', pour l'environnement '{{ dsc_name }}'."
      - ""
      - "Une fois ces vérifications et ajustements réalisés, poussez les fichiers modifiés dans votre dépôt Git (via 'git push')."
      - ""
      - "Pour finir vous pouvez soit :"
      - "- Lancer le role d'installation restant via le tag 'dso-app'."
      - "- Positionner le paramètre global.gitOps.watchpointEnabled à false dans"
      - "  votre resource dsc '{{ dsc_name }}' puis relancer une installation complète."

- name: Break execution
  ansible.builtin.meta: end_play
