---
vault_secrets_post_install: true
envs:
  - name: "{{ dsc_name }}"
    apps:
      - argocd_app: "vault"
        vault_values:
          vaultToken: >-
            {{
              (vault_keys.resources[0].data.root_token)
              if vault_keys.resources[0].data.root_token is defined and
              vault_keys.resources[0].data.root_token | length > 0
              else ''
            }}
      - argocd_app: "console"
        vault_values:
          uri: >-
            {{
              (pg_console_db_secret.resources[0].data.uri | b64decode)
              if pg_console_db_secret is defined and
              pg_console_db_secret.resources | length > 0
              else ''
            }}
