---
- name: Credentials to vault
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Get socle config from conf-dso dsc (default)"
      kubernetes.core.k8s_info:
        kind: dsc
        name: conf-dso
        api_version: cloud-pi-native.fr/v1alpha
      register: socle_config
      tags:
        - always

    - name: Get socle config from dsc_cr extra var when defined
      when: dsc_cr is defined
      kubernetes.core.k8s_info:
        kind: dsc
        name: "{{ dsc_cr }}"
        api_version: cloud-pi-native.fr/v1alpha
      register: socle_config_custom
      tags:
        - always

    - name: Check socle_config_custom and exit if empty
      when: (dsc_cr is defined) and (socle_config_custom.resources | length == 0)
      tags:
        - always
      block:
        - name: Warning message
          ansible.builtin.debug:
            msg:
              - "Attention ! Vous avez lancé le playbook avec l'option '-e dsc_cr={{ dsc_cr }}'"
              - "mais la ressource dsc nommée '{{ dsc_cr }}' est vide ou inexistante côté cluster !"
              - ""
              - "Vérifiez que vous ne vous êtes pas trompé de nom et que la ressource existe bien, via la commande suivante :"
              - ""
              - " kubectl get dsc {{ dsc_cr }} "
              - ""
              - "Si elle n'est pas trouvée (not found), listez simplement les resources dsc actuellement déclarées :"
              - ""
              - " kubectl get dsc "
              - ""
              - "Puis relancez le playbook avec une resource dsc existante."
              - ""
              - "Rappel : le présent playbook lancé seul, sans extra vars, écrira dans le Vault d'infrastructure les credentials associés à la configuration dsc par défaut (conf-dso)."

        - name: Exit playbook
          ansible.builtin.meta: end_play

    - name: Set socle_config fact when dsc_cr defined and not empty
      ansible.builtin.set_fact:
        socle_config: "{{ socle_config_custom }}"
      when: (socle_config_custom is not skipped) and (socle_config_custom.resources | length > 0)
      tags:
        - always

    - name: Set DSC facts
      ansible.builtin.set_fact:
        dsc_name: "{{ socle_config.resources[0].metadata.name }}"
        dsc: "{{ socle_config.resources[0] }}"
        dsc_default_config: "{{ lookup('ansible.builtin.file', '../roles/socle-config/files/config.yaml') | from_yaml }}"
        dsc_default_releases: "{{ lookup('ansible.builtin.file', '../roles/socle-config/files/releases.yaml') | from_yaml }}"
      tags:
        - always

    - name: Combine DSC with config and releases
      ansible.builtin.set_fact:
        dsc: "{{ (dsc_default_releases | combine(dsc_default_config, recursive=True) | combine(dsc, recursive=True)).spec }}"
      tags:
        - always

    - name: Get DSO config Secret from DSO console namespace
      kubernetes.core.k8s_info:
        kind: Secret
        name: dso-config
        namespace: "{{ dsc.console.namespace }}"
      register: dso_console_config
      tags:
        - always

    # Reusing some tasks from gitops/local-config

    - name: Check infrastructure cluster access
      when: lookup('ansible.builtin.env', 'KUBECONFIG_INFRA') | length == 0
      block:
        - name: Missing "KUBECONFIG_INFRA" environment variable
          ansible.builtin.debug:
            msg:
              - "La variable d'environnement KUBECONFIG_INFRA n'est pas définie."
              - "Veuillez la définir avec le chemin absolu vers votre kubeconfig pour accéder au cluster d'admnistration (Argo CD et Vault d'infra)."

        - name: Exit playbook
          ansible.builtin.meta: end_play

    - name: "Déclaration du kubeconfig infra"
      ansible.builtin.set_fact:
        kubeconfig_infra: "{{ lookup('ansible.builtin.env', 'KUBECONFIG_INFRA') }}"

    - name: Check infrastructure cluster access
      when: lookup('ansible.builtin.env', 'KUBECONFIG_PROXY_INFRA') | length == 0
      block:
        - name: Undefined "KUBECONFIG_PROXY_INFRA" environment variable
          ansible.builtin.debug:
            msg:
              - "La variable d'environnement KUBECONFIG_PROXY_INFRA n'est pas définie."
              - "Elle est nécessaire en cas d'utilisation de tsh proxy kube."
              - "Dans ce cas, veuillez la définir avec la valeur requises pour accéder au cluster d'admnistration (Argo CD et Vault d'infra)."

    - name: "Déclaration du kubeconfig proxy infra"
      when: lookup('ansible.builtin.env', 'KUBECONFIG_PROXY_INFRA') | length > 0
      ansible.builtin.set_fact:
        kubeconfig_proxy_infra: "{{ lookup('ansible.builtin.env', 'KUBECONFIG_PROXY_INFRA') }}"

    # Reusing some tasks from socle-config

    - name: Set root_domain fact from dsc global config
      ansible.builtin.set_fact:
        root_domain: "{{ dsc.global.rootDomain }}"

    - name: Set infra_root_domain fact from dsc global config
      ansible.builtin.set_fact:
        infra_root_domain: "{{ dsc.global.infraRootDomain }}"

    - name: Set vault_domain fact from dsc config
      ansible.builtin.set_fact:
        vault_domain: "{{ dsc.vault.domain | default(dsc.vault.subDomain ~ root_domain) }}"

    - name: Set Vault infra domain fact from environment variable
      when: lookup('ansible.builtin.env', 'VAULT_INFRA_DOMAIN') | length > 0
      ansible.builtin.set_fact:
        vaultinfra_domain: "{{ lookup('ansible.builtin.env', 'VAULT_INFRA_DOMAIN') }}"

    - name: Set Vault infra domain fact from dsc config when environment variable not set
      when: lookup('ansible.builtin.env', 'VAULT_INFRA_DOMAIN') | length == 0
      ansible.builtin.set_fact:
        vaultinfra_domain: "{{ dsc.vaultInfra.domain | default(dsc.vaultInfra.subDomain ~ infra_root_domain) }}"

    - name: Set Vault infra token fact
      ansible.builtin.include_role:
        name: shared_tasks
      vars:
        shared_tasks_run: vault-infra-token.yaml

    - name: Probe Vault infra domain cert validity
      ansible.builtin.uri:
        url: "https://{{ vaultinfra_domain }}"
        method: GET
        return_content: false
        validate_certs: true
      register: vaultinfra_probe
      ignore_errors: true

    - name: Set Vault infra certificate validity fact based on domain probe result
      ansible.builtin.set_fact:
        vaultinfra_cert_valid: "{{ vaultinfra_probe.failed is not defined or not vaultinfra_probe.failed }}"

    - name: Debug vaultinfra_domain fact
      ansible.builtin.debug:
        msg:
          - "vaultinfra_domain: {{ vaultinfra_domain }}"

    - name: Set vaultinfra_kv_name fact
      ansible.builtin.set_fact:
        vaultinfra_kv_name: "dso-{{ dsc.global.gitOps.envName }}"

    - name: Import ca role
      ansible.builtin.import_role:
        name: ca

    # Managing yaml file and envs

    - name: Check if /tmp/my-credentials.yaml exists
      ansible.builtin.file:
        state: file
        path: /tmp/my-credentials.yaml
      register: tmp_file
      ignore_errors: true

    - name: Manage /tmp/my-credentials.yaml file if absent
      when: tmp_file.state == 'absent'
      block:
        - name: Copy credentials template to /tmp
          ansible.builtin.copy:
            content: "{{ lookup('ansible.builtin.template', './templates/my-credentials-example.yaml') }}"
            dest: /tmp/my-credentials.yaml
            mode: "0600"

        - name: Dislay warning message
          ansible.builtin.debug:
            msg: |
              "
              Le fichier /tmp/my-credentials.yaml vient d'être créé.

              Veuillez le remplir avec les credentials requis puis relancer le playbook.
              "

        - name: Terminate playbook execution
          ansible.builtin.meta:
            end_play

    - name: Set envs facts from yaml file
      ansible.builtin.set_fact:
        envs: "{{ lookup('ansible.builtin.template', '/tmp/my-credentials.yaml') | from_yaml }}"

    # Reusing some tasks from gitops/vault-secrets

    - name: Retrieve Vault infra token
      ansible.builtin.include_role:
        name: shared_tasks
      vars:
        shared_tasks_run: vault-infra-token.yaml

    - name: Write secrets
      ansible.builtin.include_tasks: ../roles/gitops/vault-secrets/tasks/write.yml
      loop: "{{ envs | subelements('apps') }}"
      loop_control:
        label: "{{ item.0.name }}"
      vars:
        vault_secrets_post_install: true
        post_vault_update: true
