---
- name: Reset Keycloak admin password
  hosts: localhost
  gather_facts: false
  tasks:

    - name: "Get socle config from conf-dso dsc (default)"
      kubernetes.core.k8s_info:
        kind: dsc
        name: conf-dso
        api_version: cloud-pi-native.fr/v1alpha
      register: socle_config

    - name: Get socle config from dsc_cr extra var when defined
      when: dsc_cr is defined
      kubernetes.core.k8s_info:
        kind: dsc
        name: "{{ dsc_cr }}"
        api_version: cloud-pi-native.fr/v1alpha
      register: socle_config_custom

    - name: Check socle_config_custom and exit if empty
      when: (dsc_cr is defined) and (socle_config_custom.resources | length == 0)
      block:
        - name: Warning message
          ansible.builtin.debug:
            msg:
              - "Attention ! Vous avez lancé le playbook avec l'option '-e dsc_cr={{ dsc_cr }}'"
              - "mais la ressource dsc nommée '{{ dsc_cr }}' est vide ou inexistante côté cluster !"
              - ""
              - "Vérifiez que vous ne vous êtes pas trompé de nom et que la ressource existe bien, via la commande suivante :"
              - ""
              - " kubectl get dsc {{ dsc_cr }} "
              - ""
              - "Si elle n'est pas trouvée (not found), listez simplement les ressources dsc actuellement déclarées :"
              - ""
              - " kubectl get dsc "
              - ""
              - "Puis relancez le playbook avec une ressource dsc existante."
              - ""
              - "Rappel : le présent playbook lancé seul, sans extra vars, utilisera la configuration dsc par défaut (conf-dso)."
              - "Il réinitialisera donc le mot de passe de l'administrateur Keycloak du namespace associé."

        - name: Exit playbook
          ansible.builtin.meta: end_play

    - name: Set socle_config fact when dsc_cr defined and not empty
      ansible.builtin.set_fact:
        socle_config: "{{ socle_config_custom }}"
      when: (socle_config_custom is not skipped) and (socle_config_custom.resources | length > 0)

    - name: Set DSC facts
      ansible.builtin.set_fact:
        dsc_name: "{{ socle_config.resources[0].metadata.name }}"
        dsc: "{{ socle_config.resources[0] }}"
        dsc_default_config: "{{ lookup('ansible.builtin.file', '../roles/socle-config/files/config.yaml') | from_yaml }}"
        dsc_default_releases: "{{ lookup('ansible.builtin.file', '../roles/socle-config/files/releases.yaml') | from_yaml }}"

    - name: Combine DSC with config and releases
      ansible.builtin.set_fact:
        dsc: "{{ (dsc_default_releases | combine(dsc_default_config, recursive=True) | combine(dsc, recursive=True)).spec }}"

    - name: Get Keycloak pods
      kubernetes.core.k8s_info:
        namespace: "{{ dsc.keycloakInfra.namespace }}"
        kind: Pod
        label_selectors:
          - app.kubernetes.io/instance=keycloak
      register: kc_pods

    - name: Set kc_pod fact
      ansible.builtin.set_fact:
        kc_pod: "{{ kc_pods.resources[0].metadata.name }}"

    - name: Set tmp_adm_pass fact
      ansible.builtin.set_fact:
        tmp_adm_pass: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"

    - name: Set kc_adm_pass fact
      ansible.builtin.set_fact:
        kc_adm_pass: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"

    - name: Create temporary admin user
      kubernetes.core.k8s_exec:
        pod: "{{ kc_pod }}"
        namespace: "{{ dsc.keycloakInfra.namespace }}"
        command: >
          bash -c "JAVA_OPTS_APPEND='-Djgroups.dns.query=keycloak-headless.{{ dsc.keycloakInfra.namespace }}.svc.cluster.local -Djgroups.bind.port=7900';
          export PASS_VAR='{{ tmp_adm_pass }}';
          kc.sh bootstrap-admin user --username tmpadm --password:env PASS_VAR"
      register: tmp_adm

    - name: Update admininfra user
      community.general.keycloak_user:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: https://{{ dsc.keycloakInfra.subDomain }}{{ dsc.global.rootDomain }}
        auth_realm: master
        auth_username: tmpadm
        auth_password: "{{ tmp_adm_pass }}"
        state: present
        realm: master
        credentials:
          - temporary: false
            type: password
            value: "{{ kc_adm_pass }}"
        username: admininfra
        first_name: Admin
        last_name: Admin
        email: admin@example.com
        enabled: true
        email_verified: true
        groups:
          - name: admin
            state: present
        force: true

    - name: Update keycloak secret
      kubernetes.core.k8s:
        kind: Secret
        name: keycloak
        namespace: "{{ dsc.keycloakInfra.namespace }}"
        state: patched
        definition:
          data:
            admin-password: "{{ kc_adm_pass | b64encode }}"

    - name: Remove temporary admin from master realm
      community.general.keycloak_user:
        validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
        auth_client_id: admin-cli
        auth_keycloak_url: https://{{ dsc.keycloakInfra.subDomain }}{{ dsc.global.rootDomain }}
        auth_realm: master
        auth_username: admininfra
        auth_password: "{{ kc_adm_pass }}"
        state: absent
        realm: master
        username: tmpadm

    - name: Keycloak admin password changed
      ansible.builtin.debug:
        msg:
          - "Réinitialisation du mot de passe administrateur de l'instancce Keycloak suivante effectué :"
          - "    URL : https://{{ dsc.keycloakInfra.subDomain }}{{ dsc.global.rootDomain }}"
          - "    Namespace : {{ dsc.keycloakInfra.namespace }}"
          - ""
          - "Nouveaux identifiants :"
          - "    Utilisateur : admininfra "
          - "    Mot de passe : {{ kc_adm_pass }} "
