---
- name: Keycloak extract users
  hosts: localhost
  gather_facts: false
  vars:
    post_conf_job: true
    argo_infra_ns_check:
      failed: true
  tasks:
    - name: Import socle-config role
      ansible.builtin.import_role:
        name: socle-config

    - name: Import keycloak-extract-users role
      ansible.builtin.import_role:
        name: admin-tools/keycloak-extract-users
