---
- name: Define template dsc.json.j2 path
  ansible.builtin.set_fact:
    json_template_path: "{{ role_path }}/config/dsc.json.j2"

- name: Render dsc.json.j2 into local repository
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', json_template_path) | from_json | to_json(indent=2) }}"
    dest: "{{ gitops_local_repo }}/{{ dsc.global.gitOps.repo.path }}/envs/{{ envs[0].name }}/{{ socle_config.resources[0].metadata.name }}.json"
    mode: "0644"
  vars:
    envs:
      - name: "{{ dsc_name }}"
        apps:
          - argocd_app: "global"
            clusterName: ""
            nameSpace: "global"
            customPrefix: ""
            syncWave: 5
          - argocd_app: keycloak
            clusterName: ""
            nameSpace: "keycloak"
            customPrefix: ""
            syncWave: 10
          - argocd_app: vault
            clusterName: ""
            nameSpace: "vault"
            customPrefix: ""
            syncWave: 10
          - argocd_app: sonarqube
            clusterName: ""
            nameSpace: "sonarqube"
            customPrefix: ""
            syncWave: 10
          - argocd_app: harbor
            clusterName: ""
            nameSpace: "harbor"
            customPrefix: ""
            syncWave: 10
          - argocd_app: nexus
            clusterName: ""
            nameSpace: "nexus"
            customPrefix: ""
            syncWave: 10
          - argocd_app: glexporter
            clusterName: ""
            nameSpace: "gitlab"
            customPrefix: ""
            syncWave: 10
          - argocd_app: gitlabrunner
            clusterName: ""
            nameSpace: "gitlab"
            customPrefix: ""
            syncWave: 10
          - argocd_app: argocd
            clusterName: ""
            nameSpace: "argocd"
            customPrefix: ""
            syncWave: 10
          - argocd_app: observability
            clusterName: "in-cluster"
            nameSpace: "argo"
            customPrefix: "infra-"
            syncWave: 10
          - argocd_app: certmanager
            clusterName: ""
            nameSpace: "certmanager"
            customPrefix: ""
            syncWave: 10
          - argocd_app: gitlaboperator
            clusterName: ""
            nameSpace: "gitlab"
            customPrefix: ""
            syncWave: 10
          - argocd_app: console
            clusterName: ""
            nameSpace: "console"
            customPrefix: ""
            syncWave: 10
