---
- name: Preliminary tasks
  when: post_conf_job is not defined
  ansible.builtin.include_tasks: ./preliminary.yml

- name: Generate dsc.json
  when: post_conf_job is not defined
  ansible.builtin.include_tasks: ./generate_dsc_json.yml

- name: Loop over services to render templates
  ansible.builtin.include_tasks: ./template.yml
  loop: "{{ envs | subelements('apps') }}"
  loop_control:
    label: "{{ item.0.name }}"
