---
- name: Preliminary tasks
  ansible.builtin.include_tasks: ./preliminary.yml

- name: Loop over services to render templates
  ansible.builtin.include_tasks: ./template.yml
  loop: "{{ envs | subelements('apps') }}"
  loop_control:
    label: "{{ item.0.name }}"
  vars:
    envs:
      - name: "{{ dsc_name }}"
        apps:
          - argocd_app: global
          - argocd_app: keycloak
          - argocd_app: vault
          - argocd_app: sonarqube
          - argocd_app: observability
          - argocd_app: harbor
          - argocd_app: gitlabrunner
          - argocd_app: glexporter
          - argocd_app: argocd
          - argocd_app: nexus
          - argocd_app: certmanager
          - argocd_app: gitlaboperator
