---
- name: Set repo type fact
  ansible.builtin.set_fact:
    is_oci_repo: "{{ dsc.argocdInfra.helmRepoUrl.startswith('oci://') }}"
    repo_name: "argo" # for HTTP repositories

- name: Get Argo CD infra app version (HTTP)
  when: not is_oci_repo
  block:
    - name: Add Argo CD Helm repo (HTTP repo only)
      changed_when: false
      kubernetes.core.helm_repository:
        name: "{{ repo_name }}"
        repo_url: "{{ dsc.argocdInfra.helmRepoUrl }}"
        force_update: true

    - name: Retrieve Argo CD Helm chart info (HTTP)
      changed_when: false
      ansible.builtin.command: >-
        helm search repo {{ repo_name }}/argo-cd --version "{{ dsc.argocdInfra.chartVersion }}"
      register: argo_infos
      ignore_errors: true

    - name: Fail if chart version retrieval failed (HTTP)
      when: argo_infos.rc != 0 or argo_infos.stdout == ""
      ansible.builtin.fail:
        msg: >-
          Failed to retrieve Argo CD Helm chart version.
          Check the repository URL ({{ dsc.argocdInfra.helmRepoUrl }}) and chart version ({{ dsc.argocdInfra.chartVersion }}).

    - name: Set argo_app_version fact (HTTP)
      ansible.builtin.set_fact:
        argo_app_version: >-
          {{ argo_infos.stdout | regex_search('v([0-9]+\\.[0-9]+\\.[0-9]+)') }}

- name: Get Argo CD infra app version (OCI)
  when: is_oci_repo
  block:
    - name: Retrieve Argo CD Helm chart info (OCI)
      changed_when: false
      ansible.builtin.command: >-
        helm show chart {{ dsc.argocdInfra.helmRepoUrl }}/argo-cd --version "{{ dsc.argocdInfra.chartVersion }}"
      register: argo_infos
      ignore_errors: true

    - name: Fail if chart version retrieval failed (OCI)
      when: argo_infos.rc != 0 or argo_infos.stdout == ""
      ansible.builtin.fail:
        msg: >-
          Failed to retrieve Argo CD Helm chart version.
          Check the repository URL ({{ dsc.argocdInfra.helmRepoUrl }}) and chart version ({{ dsc.argocdInfra.chartVersion }}).

    - name: Set argo_app_version fact (OCI)
      ansible.builtin.set_fact:
        argo_app_version: "{{ argo_infos.stdout | regex_search('(?<=appVersion: )v([0-9]+\\.[0-9]+\\.[0-9]+)') }}"

- name: Find argo crd existence
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: applications.argoproj.io
  register: argocd_crd

- name: Set argo_infra_ownership fact
  ansible.builtin.set_fact:
    argo_infra_ownership: >-
      {{ (argocd_crd.resources | length > 0 and
          'meta.helm.sh/release-namespace' in argocd_crd.resources[0].metadata.annotations and
          argocd_crd.resources[0].metadata.annotations['meta.helm.sh/release-namespace'] == "{{ dsc.argocdInfra.namespace }}") | bool }}

# GitLab instance template generation

- name: Set path fact
  ansible.builtin.set_fact:
    path: "{{ role_path + '/gitlab/values' }}"

- name: Compute GitLab Helm values
  ansible.builtin.include_role:
    name: combine
  vars:
    combine_path: "{{ path }}"
    combine_user_values: "{{ dsc.gitlab['values'] }}"
    combine_dest_var: "gitlab_values"

- name: Set gitlab_definition fact
  ansible.builtin.set_fact:
    gitlab_definition: "{{ content }}"
  vars:
    content:
      apiVersion: apps.gitlab.com/v1beta1
      kind: GitLab
      metadata:
        name: gitlab
        namespace: "{{ dsc.gitlab.namespace }}"
        annotations:
          argocd.argoproj.io/sync-wave: "5"
      spec:
        chart:
          version: "{{ dsc.gitlab.chartVersion }}"
          values: "{{ gitlab_values }}"

- name: Create destination dir
  ansible.builtin.file:
    path: "{{ gitops_local_repo }}/{{ dsc.global.gitOps.repo.path }}/envs/{{ envs[0].name }}/apps/gitlab/templates"
    state: directory
    mode: "0775"

- name: Render gitlab instance file into GitOps local repo
  ansible.builtin.copy:
    content: "{{ gitlab_definition | to_nice_yaml(indent=2) }}"
    dest: "{{ gitops_local_repo }}/{{ dsc.global.gitOps.repo.path }}/envs/{{ envs[0].name }}/apps/gitlab/templates/gitlab.yaml"
    mode: "0644"
